import React, { useState } from "react";
import { FaSearch } from "react-icons/fa";

const Reporting = () => {
  const [search, setSearch] = useState("");

  return (
    <div className="bg-gray-50">
      <div className="max-w-6xl mx-auto bg-white rounded-lg shadow-sm p-4">
        
        {/* Header */}
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-base sm:text-lg font-bold text-gray-900">
            Reporting
          </h2>

          {/* Search box (right corner) */}
          <div className="relative w-64">
<input
  type="text"
  placeholder="खोजें"
  value={search}
  onChange={(e) => setSearch(e.target.value)}
  className="w-full pl-8  pr-3 py-1  text-sm border border-gray-300 rounded-md
             focus:outline-none focus:ring-1 focus:ring-blue-500
             kruti-input"
/>



            <FaSearch className="absolute left-2.5 top-1/2 -translate-y-1/2 text-gray-400 text-xs" />
          </div>
        </div>

        {/* Table */}
        <div className="overflow-x-auto rounded-md  ">
          <table className="min-w-full text-sm text-left">
            <thead className="bg-gray-100 text-gray-700">
              <tr>
                <th className="px-4 py-2">S.No</th>
                <th className="px-4 py-2">Report ID</th>
                <th className="px-4 py-2">Report Name</th>
                <th className="px-4 py-2">Generated By</th>
                <th className="px-4 py-2">Date</th>
                <th className="px-4 py-2">Status</th>
              </tr>
            </thead>

            <tbody className="divide-y divide-gray-200">
              {[1, 2, 3, 4, 5].map((_, index) => (
                <tr key={index} className="hover:bg-gray-50">
                  <td className="px-4 py-2">{index + 1}</td>
                  <td className="px-4 py-2 font-medium">
                    REP-000{index + 1}
                  </td>
                  <td className="px-4 py-2 text-blue-600 font-medium">
                    Monthly Status Report
                  </td>
                  <td className="px-4 py-2">
                    Record Section
                  </td>
                  <td className="px-4 py-2 text-gray-600">
                    16 Feb 2026
                  </td>
                  <td className="px-4 py-2">
                    <span className="px-2 py-0.5 rounded-full text-xs font-semibold
                                     bg-green-100 text-green-700">
                      Generated
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

      </div>
    </div>
  );
};

export default Reporting;
