import React, { useState } from "react";
import { FaSearch } from "react-icons/fa";

const Reporting = () => {
  // Nayi combined states
  const [compFile, setCompFile] = useState(""); // Complaint No & File No ke liye
  const [corrResp, setCorrResp] = useState(""); // Correspondence & Respondence ke liye
  const [date, setDate] = useState("");
  const [year, setYear] = useState("");

  return (
    <div className="bg-gray-50">
      <div className="max-w-6xl mx-auto bg-white rounded-lg shadow-sm p-4">
        
        {/* Header & Search Filters */}
        <div className="flex flex-col lg:flex-row lg:items-center justify-between mb-4 gap-4">
          <h2 className="text-base sm:text-lg font-bold text-gray-900 whitespace-nowrap">
            Reporting
          </h2>

          {/* Updated Search fields */}
          <div className="flex flex-wrap items-center gap-3">
            
            {/* Complaint No / File No Combined Input */}
            <input
              type="text"
              placeholder="Complaint / File No"
              value={compFile}
              onChange={(e) => setCompFile(e.target.value)}
              className="w-40 px-3 py-1.5 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500"
            />

            {/* Correspondence / Respondence Combined Input */}
            <input
              type="text"
              placeholder="Corr. / Respondence"
              value={corrResp}
              onChange={(e) => setCorrResp(e.target.value)}
              className="w-40 px-3 py-1.5 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500"
            />
            
            {/* Date Input */}
            <input
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              className="w-36 px-3 py-1.5 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 text-gray-600"
            />
            
            {/* Year Input (Date jaisa feel dene ke liye type="number" use kiya hai) */}
            <input
              type="number"
              placeholder="Year (YYYY)"
              min="1990"
              max="2099"
              value={year}
              onChange={(e) => setYear(e.target.value)}
              className="w-28 px-3 py-1.5 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500"
            />
            
            <button className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-1.5 rounded-md text-sm font-medium transition-colors">
              <FaSearch className="text-xs" />
              Search
            </button>
          </div>
        </div>

        {/* Table (Purana Code, Koi change nahi kiya gaya hai) */}
        <div className="overflow-x-auto rounded-md">
          <table className="min-w-full text-sm text-left">
            <thead className="bg-gray-100 text-gray-700">
              <tr>
                <th className="px-4 py-2">S.No</th>
                <th className="px-4 py-2">File No</th>
                <th className="px-4 py-2">Report Name</th>
                <th className="px-4 py-2">Generated By</th>
                <th className="px-4 py-2">Date</th>
                <th className="px-4 py-2">Status</th>
              </tr>
            </thead>

            <tbody className="divide-y divide-gray-200">
              {[1, 2, 3, 4, 5].map((_, index) => (
                <tr key={index} className="hover:bg-gray-50">
                  <td className="px-4 py-2">{index + 1}</td>
                  <td className="px-4 py-2 font-medium">
                    FILE-000{index + 1}
                  </td>
                  <td className="px-4 py-2 text-blue-600 font-medium">
                    Monthly Status Report
                  </td>
                  <td className="px-4 py-2">
                    Record Section
                  </td>
                  <td className="px-4 py-2 text-gray-600">
                    16 Feb 2026
                  </td>
                  <td className="px-4 py-2">
                    <span className="px-2 py-0.5 rounded-full text-xs font-semibold
                                     bg-green-100 text-green-700">
                      Generated
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

      </div>
    </div>
  );
};

export default Reporting;